# Generated by Django 6.0.4 on 2026-04-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="fotografia",
        ),
        migrations.AddField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(default=None, upload_to="cursos/"),
            preserve_default=False,
        ),
    ]
