# Generated by Django 6.0.4 on 2026-04-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("nivel", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("pagina_pessoal", models.URLField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("sigla", models.CharField(max_length=20)),
                ("instituicao", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("duracao_anos", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PalavraChave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("logo", models.ImageField(upload_to="tecnologias/")),
                ("website_url", models.URLField()),
                ("nivel_preferencia", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Utilizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="utilizadores/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("instituicao", models.CharField(max_length=150)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("certificado_url", models.URLField(blank=True)),
                ("descricao", models.TextField()),
                (
                    "competencias",
                    models.ManyToManyField(blank=True, to="portfolio.competencia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("codigo", models.CharField(max_length=20)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(blank=True, to="portfolio.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                ("imagem", models.ImageField(upload_to="projetos/")),
                ("video_demo", models.URLField(blank=True)),
                ("conceitos_aplicados", models.TextField()),
                (
                    "competencias",
                    models.ManyToManyField(blank=True, to="portfolio.competencia"),
                ),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portfolio.uc"
                    ),
                ),
                (
                    "utilizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.utilizador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("classificacao", models.IntegerField()),
                ("pdf", models.URLField(blank=True)),
                ("imagem", models.ImageField(upload_to="tfc/")),
                ("areas", models.ManyToManyField(blank=True, to="portfolio.area")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.licenciatura",
                    ),
                ),
                ("orientadores", models.ManyToManyField(to="portfolio.docente")),
                (
                    "palavras_chave",
                    models.ManyToManyField(blank=True, to="portfolio.palavrachave"),
                ),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
                (
                    "autores",
                    models.ManyToManyField(
                        related_name="tfc_autores", to="portfolio.utilizador"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repositorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("url", models.URLField()),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateField()),
                ("visibilidade", models.CharField(max_length=20)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projeto",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
                (
                    "utilizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.utilizador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                ("imagem", models.ImageField(upload_to="makingof/")),
                ("decisoes", models.TextField()),
                ("erros", models.TextField()),
                ("correcoes", models.TextField()),
                ("justificacao", models.TextField()),
                ("uso_ia", models.TextField()),
                (
                    "utilizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.utilizador",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="utilizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portfolio.utilizador"
            ),
        ),
    ]
