# Generated by Django 6.0.4 on 2026-04-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="makingof/"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="projetos/"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="tfc/"),
        ),
        migrations.AlterField(
            model_name="uc",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
    ]
