# Generated by Django 6.0.4 on 2026-04-10 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_makingof_imagem_alter_projeto_imagem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="sumario",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="duracao_anos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="instituicao",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="sigla",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.ManyToManyField(
                blank=True, related_name="tfc_autores", to="portfolio.utilizador"
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="classificacao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.licenciatura",
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientadores",
            field=models.ManyToManyField(blank=True, to="portfolio.docente"),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
    ]
