# Generated by Django 6.0.4 on 2026-04-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_tfc_sumario_alter_licenciatura_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="codigo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="ects",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="licenciatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ucs",
                to="portfolio.licenciatura",
            ),
        ),
        migrations.AlterField(
            model_name="uc",
            name="semestre",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
