# Generated by Django 6.0.4 on 2026-04-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_licenciatura_codigo_uc_ects_alter_uc_ano_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uc",
            name="conteudos",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="objetivos",
            field=models.TextField(blank=True),
        ),
    ]
