# Generated by Django 6.0.5 on 2026-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_tipotecnologia_alter_tecnologia_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="nome",
            field=models.CharField(max_length=300),
        ),
    ]
