# Generated by Django 6.0.5 on 2026-05-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_docente_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palavrachave",
            name="nome",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="imagem",
            field=models.ImageField(
                blank=True, max_length=300, null=True, upload_to="tfc/"
            ),
        ),
    ]
